[package]
name = "searcher"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
rayon = "1.10.0"
#serde = {version = "1.0.210", features = ["derive"]}
serde_json = {version = "1.0.129"}
tokio = {version = "1.40.0", features = ["full"]}
futures = "0.3.31"
#num_cpus = "1.16.0"